POST http://localhost:3001/groups
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InN1cGVyX2FkbWluIiwiaWF0IjoxNjg2OTUyNjQ0LCJleHAiOjE2ODcwMzkwNDR9.T4TN-fot6x99rMmnazln2nopG8Uyt38QrqxLhkbaPAM
Content-Type: application/json

{
  "name": "N3",
  "teacher_id": 2,
  "assistent_teacher_id": 3
}

###
GET http://localhost:3001/groups/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InN1cGVyX2FkbWluIiwiaWF0IjoxNjg2OTUyNjQ0LCJleHAiOjE2ODcwMzkwNDR9.T4TN-fot6x99rMmnazln2nopG8Uyt38QrqxLhkbaPAM

###
POST http://localhost:3001/groups/2/students/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InN1cGVyX2FkbWluIiwiaWF0IjoxNjg2OTUyNjQ0LCJleHAiOjE2ODcwMzkwNDR9.T4TN-fot6x99rMmnazln2nopG8Uyt38QrqxLhkbaPAM
