### Add stuff
POST http://localhost:3001/stuff
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InN1cGVyX2FkbWluIiwiaWF0IjoxNjg2Nzk5MjcyLCJleHAiOjE2ODY4ODU2NzJ9.gtBrdZkw9JsCtDx05MkUrPaN3T2aVQEaWXvah_jgAus

{
  "first_name": "F",
  "last_name": ".....",
  "role": "teacher",
  "username": "test7",
  "password": "12345"
}

### List stuff
GET http://localhost:3001/stuff?role=teacher
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InN1cGVyX2FkbWluIiwiaWF0IjoxNjg2Nzk5MjcyLCJleHAiOjE2ODY4ODU2NzJ9.gtBrdZkw9JsCtDx05MkUrPaN3T2aVQEaWXvah_jgAus
# query params: role, q

### Show single stuff
GET http://localhost:3001/stuff/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2Mzc3NzA1LCJleHAiOjE2ODY0NjQxMDV9.zM2jDB8F7Hvf0XmzJiPgCbP-yyhz-apCF9eGbIf9jps

### Login schema
POST http://localhost:3001/stuff/login
Content-Type: application/json

{
  "username": "superadmin",
  "password": "foobarbaz"
}

### Update stuff
PATCH http://localhost:3001/stuff/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2Mzc3NzA1LCJleHAiOjE2ODY0NjQxMDV9.zM2jDB8F7Hvf0XmzJiPgCbP-yyhz-apCF9eGbIf9jps
Content-Type: application/json

{
  "first_name": "MuhammadSodiq",
  "last_name": "Mirziyoyev",
  "username": "mirziyoyev" 
}

### Delete stuff
DELETE http://localhost:3001/stuff/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjg2Mzc3NzA1LCJleHAiOjE2ODY0NjQxMDV9.zM2jDB8F7Hvf0XmzJiPgCbP-yyhz-apCF9eGbIf9jps
